### ISSUE TITLE
"Cannot find module" in temp directory when '... new myapp -b @glimmer/blueprint' on Win10

### ISSUE THREAD

**Issue by stonecooler** [glimmerjs/glimmer-blueprint#34]
Hi,

after I seen glimmer.js in action on jsconfeu last weekend I started to work through the guides from "glimmerjs.com". Installing on Win10 works fine:

```
> ember -v 
ember-cli: 2.14.0-beta.1
node: 6.10.3
os: win32 x64
```
But I got an error when creating a new app with `ember new my-app -b @glimmer/blueprint`:
```
Error creating new application. Removing generated directory `./my-app`
Cannot find module 'C:\Users\stste\AppData\Local\Temp\ember-cli11749-12384-ak8wi2.6h5llyp66r\node_modules\@glimmer\blueprint\package.json'
Error: Cannot find module 'C:\Users\stste\AppData\Local\Temp\ember-cli11749-12384-ak8wi2.6h5llyp66r\node_modules\@glimmer\blueprint\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at InstallBlueprintTask._validateNpmModule (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\ember-cli\lib\tasks\install-blueprint.js:128:15)
    at _createTempFolder.then.then.modulePath (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\ember-cli\lib\tasks\install-blueprint.js:91:14)
    at tryCatch (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\Users\stste\AppData\Local\Yarn\config\global\node_modules\rsvp\dist\rsvp.js:2414:5)
```
It seems that the generating of a temp directory during the blueprint install does not work - I guess on Win10 only? The `ember-cli...` directory is really not in  `...AppData\Local\Temp\` in the file system.

Can someone help? Thanks.

**Comment by jonatanmichiels** [comment]
I have also exact the same problem.

**Comment by alireza-salehi** [comment]
I have same issue and unable to create new app,
`C:\Users\Alireza\Desktop\test>ember -v
ember-cli: 2.14.0-beta.2
node: 6.9.4
os: win32 x64 - windows 10`


`C:\Users\Alireza\Desktop\test>npm install -g ember-cli@2.14.0-beta.1
C:\Users\Alireza\AppData\Roaming\npm\� -> C:\Users\Alireza\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
C:\Users\Alireza\AppData\Roaming\npm\ember -> C:\Users\Alireza\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
- buffer-shims@1.0.0 node_modules\ember-cli\node_modules\buffer-shims
- ms@0.7.2 node_modules\ember-cli\node_modules\morgan\node_modules\ms
- debug@2.6.1 node_modules\ember-cli\node_modules\morgan\node_modules\debug
- sync-exec@0.6.2 node_modules\ember-cli\node_modules\sync-exec
- utf8-byte-length@1.0.4 node_modules\ember-cli\node_modules\utf8-byte-length
- truncate-utf8-bytes@1.0.2 node_modules\ember-cli\node_modules\truncate-utf8-bytes
- sanitize-filename@1.6.1 node_modules\ember-cli\node_modules\sanitize-filename
C:\Users\Alireza\AppData\Roaming\npm
`-- ember-cli@2.14.0-beta.1
  +-- babel-plugin-transform-es2015-modules-amd@6.24.1
  | `-- babel-template@6.24.1
  |   `-- babylon@6.17.2
  +-- broccoli-babel-transpiler@6.0.0-alpha.3
  +-- broccoli-brocfile-loader@0.18.0
  | `-- findup-sync@0.4.3
  |   `-- micromatch@2.3.11
  |     `-- parse-glob@3.0.4
  |       `-- is-dotfile@1.0.3
  +-- broccoli-middleware@1.0.0-beta.8
  | `-- handlebars@4.0.10
  |   `-- uglify-js@2.8.28
  +-- broccoli-stew@1.5.0
  | `-- broccoli-debug@0.6.2
  +-- console-ui@1.0.3
  | `-- inquirer@1.2.3
  |   `-- external-editor@1.1.1
  |     `-- spawn-sync@1.0.15
  |       `-- concat-stream@1.6.0
  |         `-- readable-stream@2.2.10
  +-- core-object@3.1.3
  +-- ember-try@0.2.15
  | `-- ember-try-config@2.1.0
  |   `-- node-fetch@1.7.1
  +-- morgan@1.8.2
  +-- quick-temp@0.1.8
  | `-- underscore.string@3.3.4
  |   `-- sprintf-js@1.1.1
  +-- sane@1.7.0
  | `-- fb-watchman@2.0.0
  |   `-- bser@2.0.0
  +-- testem@1.16.2
  | +-- npmlog@4.1.0
  | | +-- are-we-there-yet@1.1.4
  | | | `-- readable-stream@2.2.10
  | | `-- gauge@2.7.4
  | |   `-- aproba@1.1.2
  | `-- tap-parser@5.3.3
  |   `-- readable-stream@2.2.10
  |     `-- safe-buffer@5.1.0
  `-- walk-sync@0.3.2


C:\Users\Alireza\Desktop\test>ember new my-app -b @glimmer/blueprint
Error creating new application. Removing generated directory `./my-app`
Cannot find module 'C:\Users\Alireza\AppData\Local\Temp\ember-cli11756-11916-18r3a9.leefpta9k9\node_modules\@glimmer\blueprint\package.json'
Error: Cannot find module 'C:\Users\Alireza\AppData\Local\Temp\ember-cli11756-11916-18r3a9.leefpta9k9\node_modules\@glimmer\blueprint\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at InstallBlueprintTask._validateNpmModule (C:\Users\Alireza\node_modules\ember-cli\lib\tasks\install-blueprint.js:128:15)
    at _createTempFolder.then.then.modulePath (C:\Users\Alireza\node_modules\ember-cli\lib\tasks\install-blueprint.js:91:14)
    at tryCatch (C:\Users\Alireza\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Users\Alireza\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Users\Alireza\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\Users\Alireza\node_modules\rsvp\dist\rsvp.js:2414:5)`

**Comment by alireza-salehi** [comment]
Updated to windows 10 creators update 1703, and problem fixed, or maybe it was because of ember 2.14 beta, nut it is fixed now , and i successfully executed following commands on windows 10:

`npm install -g ember-cli
ember new my-app -b @glimmer/blueprint
cd my-app 
ember s`

**Comment by jonatanmichiels** [comment]
Still not fixed

I have installed winddows creators update 1703
ember-cli: 2.14.0
node: 6.9.1
npm: 5.3.0

also the latest version of yarn is installed but I still get this error:

`
PS D:\Tryouts> ember new glimmer-tryout -b @glimmer/blueprint
Error creating new application. Removing generated directory `./glimmer-tryout`
Cannot find module 'C:\Users\michi\AppData\Local\Temp\ember-cli117618-12652-1n9o2l4.4k21emi\node_modules\@glimmer\blueprint\package.json'
Error: Cannot find module 'C:\Users\michi\AppData\Local\Temp\ember-cli117618-12652-1n9o2l4.4k21emi\node_modules\@glimmer\blueprint\package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at InstallBlueprintTask._validateNpmModule (C:\Users\michi\AppData\Roaming\npm\node_modules\ember-cli\lib\tasks\install-blueprint.js:128:15)
    at _createTempFolder.then.then.modulePath (C:\Users\michi\AppData\Roaming\npm\node_modules\ember-cli\lib\tasks\install-blueprint.js:91:14)
    at tryCatch (C:\Users\michi\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\michi\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\michi\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\michi\AppData\Roaming\npm\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2400:5)
`

**Comment by acorncom** [comment]
Is this still an issue for people? I don't have ready access to Windows to double-check myself

**Comment by jongalloway** [comment]
I'm still having trouble with it - exact same error as reported above.

**Comment by CheoWalker** [comment]
I have the same issue

**Comment by forbesmyester** [comment]
I'm getting this on Debian Stretch

**Comment by t-sauer** [comment]
A workaround for this problem is to create the app while skipping the installation step (i.e. `ember new .... --skip-npm`) and install the dependencies afterwards (just run `yarn`). The default dependency installation step skips optional dependencies and that seems to be the problem here.
